import { createComponent, getTitle } from '../../.storybook/templates';
import { includeseventlisthtml as component } from '../../.storybook/generatedIncludes';

const options = getTitle({
  title: 'Event List',
});

export default {
  ...options,
};

const Template = (args) => createComponent(args, component);

export const EventList = Template.bind({});

EventList.args = {
  list: [
    {
      headline: 'Neue Headline 2. Thema, maximal 2 Zeilig',
      content:
        '<ul><li>I always had an optimism that was hard for others</li><li>Even in the midst of the all the negative influences from family TWhen I was a young man, even a teenager for that matter, I always had an optimism that was</li></ul>',
      date: '16.02.2022',
      time: '14-15 Uhr',
      shapes: [
        {
          color: 'var(--color-green-blue)',
        },
        {
          color: 'var(--color-yellow)',
        },
      ],
      webcast: true,
      authors: 'Mit Nadine Kern & Max Mustermann',
      image: {
        img: '/events/authors/authors-demo.png',
        alt: 'lorem ipsum',
      },
      badge: {
        text: 'Neuer Webcast',
        icon: '',
      },
      cta: {
        text: 'Jetzt anmelden',
        href: 'javascript:void(0)',
        skin: 'primary',
        button: true,
      },
    },
    {
      headline: 'Neue Headline 2. Thema, maximal 2 Zeilig',
      content:
        '<ul><li>I always had an optimism that was hard for others</li><li>Even in the midst of the all the negative influences from family TWhen I was a young man, even a teenager for that matter, I always had an optimism that was</li></ul>',
      date: '16.02.2022',
      time: '14-15 Uhr',
      shapes: [
        {
          color: 'var(--color-green-blue)',
        },
        {
          color: 'var(--color-yellow)',
        },
      ],
      webcast: true,
      authors: 'Mit Nadine Kern & Max Mustermann',
      image: {
        img: '/events/authors/authors-demo.png',
        alt: 'lorem ipsum',
      },
      badge: {
        text: 'Neuer Webcast',
        icon: '',
      },
      cta: {
        text: 'Jetzt anmelden',
        href: 'javascript:void(0)',
        skin: 'primary',
        button: true,
      },
    },
    {
      headline: 'Microsoft 365 Holistic Workplace Security via Teams Meeting',
      time: '1-4 Tage',
      shapes: {},
      authors: 'Mit Nadine Kern & Max Mustermann',
      image: {
        img: '/events/authors/authors-demo.png',
        alt: 'lorem ipsum',
      },
      badge: {
        text: 'Training',
        color: 'var(--color-sunglow)',
      },
      price: 'Kostenlos',
    },
  ],
  settings: [
    { variant: 6 },
    { variant: 6 },
    {
      variant: 8,
      teaser: {
        teaser: true,
        headline: 'Eigenes Training Lorem Ipsum dolor Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
        content:
          '<ul><li>I always had an optimism that was hard for others</li><li>Even in the midst of the all the negative influences from family TWhen I was a young man, even a teenager for that matter, I always had an optimism that was</li></ul>',
        color: '#ff0000',
        cta: {
          text: 'Schulungen anfragen',
          href: 'javascript:void(0)',
          skin: 'primary',
          button: true,
        },
      },
    },
    { variant: 4 },
  ],
};

var test = [
  {
    tags: [],
    content:
      '<p>Even in the midst of the all the negative influences from family TWhen I was a young man, even a teenager for that matter, I always had an optimism that was</p>\n\n',
    collection: 'events',
    url: '/events/2022-02-16-neuer-webcast%20copy%202/',
    relative_path: '_events/2022-02-16-neuer-webcast copy 2.md',
    next: {
      tags: [],
      content:
        '<ul><li>I always had an optimism that was hard for others</li><li>Even in the midst of the all the negative influences from family TWhen I was a young man, even a teenager for that matter, I always had an optimism that was</li></ul>\n',
      collection: 'events',
      url: '/events/2022-02-16-neuer-webcast%20copy/',
      relative_path: '_events/2022-02-16-neuer-webcast copy.md',
      next: {
        tags: [],
        collection: 'events',
        url: '/events/2022-02-16-neuer-webcast/',
        relative_path: '_events/2022-02-16-neuer-webcast.md',
        path: '_events/2022-02-16-neuer-webcast.md',
        date: '2022-02-16 00:00:00 +0100',
        title: 'Neue Headline 2. Thema, maximal 2 Zeilig',
        categories: [],
        id: '/events/neuer-webcast',
        draft: false,
        layout: 'event',
        eventid: 1,
        headline: 'Neue Headline 2. Thema, maximal 2 Zeilig',
        authors: 'Mit Nadine Kern & Max Mustermann',
        time: '14-15 Uhr',
        shapes: [{ color: 'var(--color-green-blue)' }, { color: 'var(--color-yellow)' }],
        webcast: true,
        image: { img: '/events/authors/authors-demo.png', alt: 'lorem ipsum' },
        badge: { text: 'Neuer Webcast', icon: '' },
        cta: { text: 'Jetzt anmelden', href: 'javascript:void(0)', skin: 'primary', button: true },
        slug: 'neuer-webcast',
        ext: '.md',
      },
      path: '_events/2022-02-16-neuer-webcast copy.md',
      previous: {
        tags: [],
        collection: 'events',
        url: '/events/2022-02-16-neuer-webcast%20copy%202/',
        relative_path: '_events/2022-02-16-neuer-webcast copy 2.md',
        path: '_events/2022-02-16-neuer-webcast copy 2.md',
        date: '2022-02-16 00:00:00 +0100',
        title: 'Microsoft 365 Holistic Workplace Security via Teams Meeting',
        categories: [],
        id: '/events/neuer-webcast copy 2',
        draft: false,
        layout: 'event',
        eventid: 3,
        headline: 'Microsoft 365 Holistic Workplace Security via Teams Meeting',
        authors: 'Mit Nadine Kern & Max Mustermann',
        time: '1-4 Tage',
        shapes: [{ color: 'var(--color-green-blue)' }, { color: 'var(--color-yellow)' }],
        webcast: true,
        image: { img: '/events/authors/authors-demo.png', alt: 'lorem ipsum' },
        badge: { text: 'Training', color: 'var(--color-sunglow)' },
        price: 'Kostenlos',
        slug: 'neuer-webcast copy 2',
        ext: '.md',
      },
      output: 'event layout\n',
      excerpt:
        '<ul><li>I always had an optimism that was hard for others</li><li>Even in the midst of the all the negative influences from family TWhen I was a young man, even a teenager for that matter, I always had an optimism that was</li></ul>\n',
      date: '2022-02-16 00:00:00 +0100',
      title: 'Neue Headline 2. Thema, maximal 2 Zeilig',
      categories: [],
      id: '/events/neuer-webcast copy',
      draft: false,
      layout: 'event',
      eventid: 2,
      headline: 'Neue Headline 2. Thema, maximal 2 Zeilig',
      authors: 'Mit Nadine Kern & Max Mustermann',
      time: '14-15 Uhr',
      shapes: [{ color: 'var(--color-green-blue)' }, { color: 'var(--color-yellow)' }],
      webcast: true,
      image: { img: '/events/authors/authors-demo.png', alt: 'lorem ipsum' },
      badge: { text: 'Neuer Webcast', icon: '' },
      cta: { text: 'Jetzt anmelden', href: 'javascript:void(0)', skin: 'primary', button: true },
      slug: 'neuer-webcast copy',
      ext: '.md',
    },
    path: '_events/2022-02-16-neuer-webcast copy 2.md',
    previous: null,
    output: 'event layout\n',
    excerpt:
      '<p>Even in the midst of the all the negative influences from family TWhen I was a young man, even a teenager for that matter, I always had an optimism that was</p>\n',
    date: '2022-02-16 00:00:00 +0100',
    title: 'Microsoft 365 Holistic Workplace Security via Teams Meeting',
    categories: [],
    id: '/events/neuer-webcast copy 2',
    draft: false,
    layout: 'event',
    eventid: 3,
    headline: 'Microsoft 365 Holistic Workplace Security via Teams Meeting',
    authors: 'Mit Nadine Kern & Max Mustermann',
    time: '1-4 Tage',
    shapes: [{ color: 'var(--color-green-blue)' }, { color: 'var(--color-yellow)' }],
    webcast: true,
    image: { img: '/events/authors/authors-demo.png', alt: 'lorem ipsum' },
    badge: { text: 'Training', color: 'var(--color-sunglow)' },
    price: 'Kostenlos',
    slug: 'neuer-webcast copy 2',
    ext: '.md',
  },
  {
    tags: [],
    content:
      '<ul><li>I always had an optimism that was hard for others</li><li>Even in the midst of the all the negative influences from family TWhen I was a young man, even a teenager for that matter, I always had an optimism that was</li></ul>\n',
    collection: 'events',
    url: '/events/2022-02-16-neuer-webcast%20copy/',
    relative_path: '_events/2022-02-16-neuer-webcast copy.md',
    next: {
      tags: [],
      content:
        '<p>Even in the midst of the all the negative influences from family TWhen I was a young man, even a teenager for that matter, I always had an optimism that was</p>\n\n',
      collection: 'events',
      url: '/events/2022-02-16-neuer-webcast/',
      relative_path: '_events/2022-02-16-neuer-webcast.md',
      next: null,
      path: '_events/2022-02-16-neuer-webcast.md',
      previous: {
        tags: [],
        collection: 'events',
        url: '/events/2022-02-16-neuer-webcast%20copy/',
        relative_path: '_events/2022-02-16-neuer-webcast copy.md',
        path: '_events/2022-02-16-neuer-webcast copy.md',
        date: '2022-02-16 00:00:00 +0100',
        title: 'Neue Headline 2. Thema, maximal 2 Zeilig',
        categories: [],
        id: '/events/neuer-webcast copy',
        draft: false,
        layout: 'event',
        eventid: 2,
        headline: 'Neue Headline 2. Thema, maximal 2 Zeilig',
        authors: 'Mit Nadine Kern & Max Mustermann',
        time: '14-15 Uhr',
        shapes: [{ color: 'var(--color-green-blue)' }, { color: 'var(--color-yellow)' }],
        webcast: true,
        image: { img: '/events/authors/authors-demo.png', alt: 'lorem ipsum' },
        badge: { text: 'Neuer Webcast', icon: '' },
        cta: { text: 'Jetzt anmelden', href: 'javascript:void(0)', skin: 'primary', button: true },
        slug: 'neuer-webcast copy',
        ext: '.md',
      },
      output: 'event layout\n',
      excerpt:
        '<p>Even in the midst of the all the negative influences from family TWhen I was a young man, even a teenager for that matter, I always had an optimism that was</p>\n',
      date: '2022-02-16 00:00:00 +0100',
      title: 'Neue Headline 2. Thema, maximal 2 Zeilig',
      categories: [],
      id: '/events/neuer-webcast',
      draft: false,
      layout: 'event',
      eventid: 1,
      headline: 'Neue Headline 2. Thema, maximal 2 Zeilig',
      authors: 'Mit Nadine Kern & Max Mustermann',
      time: '14-15 Uhr',
      shapes: [{ color: 'var(--color-green-blue)' }, { color: 'var(--color-yellow)' }],
      webcast: true,
      image: { img: '/events/authors/authors-demo.png', alt: 'lorem ipsum' },
      badge: { text: 'Neuer Webcast', icon: '' },
      cta: { text: 'Jetzt anmelden', href: 'javascript:void(0)', skin: 'primary', button: true },
      slug: 'neuer-webcast',
      ext: '.md',
    },
    path: '_events/2022-02-16-neuer-webcast copy.md',
    previous: {
      tags: [],
      content:
        '<p>Even in the midst of the all the negative influences from family TWhen I was a young man, even a teenager for that matter, I always had an optimism that was</p>\n\n',
      collection: 'events',
      url: '/events/2022-02-16-neuer-webcast%20copy%202/',
      relative_path: '_events/2022-02-16-neuer-webcast copy 2.md',
      next: {
        tags: [],
        collection: 'events',
        url: '/events/2022-02-16-neuer-webcast%20copy/',
        relative_path: '_events/2022-02-16-neuer-webcast copy.md',
        path: '_events/2022-02-16-neuer-webcast copy.md',
        date: '2022-02-16 00:00:00 +0100',
        title: 'Neue Headline 2. Thema, maximal 2 Zeilig',
        categories: [],
        id: '/events/neuer-webcast copy',
        draft: false,
        layout: 'event',
        eventid: 2,
        headline: 'Neue Headline 2. Thema, maximal 2 Zeilig',
        authors: 'Mit Nadine Kern & Max Mustermann',
        time: '14-15 Uhr',
        shapes: [{ color: 'var(--color-green-blue)' }, { color: 'var(--color-yellow)' }],
        webcast: true,
        image: { img: '/events/authors/authors-demo.png', alt: 'lorem ipsum' },
        badge: { text: 'Neuer Webcast', icon: '' },
        cta: { text: 'Jetzt anmelden', href: 'javascript:void(0)', skin: 'primary', button: true },
        slug: 'neuer-webcast copy',
        ext: '.md',
      },
      path: '_events/2022-02-16-neuer-webcast copy 2.md',
      previous: null,
      output: 'event layout\n',
      excerpt:
        '<p>Even in the midst of the all the negative influences from family TWhen I was a young man, even a teenager for that matter, I always had an optimism that was</p>\n',
      date: '2022-02-16 00:00:00 +0100',
      title: 'Microsoft 365 Holistic Workplace Security via Teams Meeting',
      categories: [],
      id: '/events/neuer-webcast copy 2',
      draft: false,
      layout: 'event',
      eventid: 3,
      headline: 'Microsoft 365 Holistic Workplace Security via Teams Meeting',
      authors: 'Mit Nadine Kern & Max Mustermann',
      time: '1-4 Tage',
      shapes: [{ color: 'var(--color-green-blue)' }, { color: 'var(--color-yellow)' }],
      webcast: true,
      image: { img: '/events/authors/authors-demo.png', alt: 'lorem ipsum' },
      badge: { text: 'Training', color: 'var(--color-sunglow)' },
      price: 'Kostenlos',
      slug: 'neuer-webcast copy 2',
      ext: '.md',
    },
    output: 'event layout\n',
    excerpt:
      '<ul><li>I always had an optimism that was hard for others</li><li>Even in the midst of the all the negative influences from family TWhen I was a young man, even a teenager for that matter, I always had an optimism that was</li></ul>\n',
    date: '2022-02-16 00:00:00 +0100',
    title: 'Neue Headline 2. Thema, maximal 2 Zeilig',
    categories: [],
    id: '/events/neuer-webcast copy',
    draft: false,
    layout: 'event',
    eventid: 2,
    headline: 'Neue Headline 2. Thema, maximal 2 Zeilig',
    authors: 'Mit Nadine Kern & Max Mustermann',
    time: '14-15 Uhr',
    shapes: [{ color: 'var(--color-green-blue)' }, { color: 'var(--color-yellow)' }],
    webcast: true,
    image: { img: '/events/authors/authors-demo.png', alt: 'lorem ipsum' },
    badge: { text: 'Neuer Webcast', icon: '' },
    cta: { text: 'Jetzt anmelden', href: 'javascript:void(0)', skin: 'primary', button: true },
    slug: 'neuer-webcast copy',
    ext: '.md',
  },
  {
    tags: [],
    content:
      '<p>Even in the midst of the all the negative influences from family TWhen I was a young man, even a teenager for that matter, I always had an optimism that was</p>\n\n',
    collection: 'events',
    url: '/events/2022-02-16-neuer-webcast/',
    relative_path: '_events/2022-02-16-neuer-webcast.md',
    next: null,
    path: '_events/2022-02-16-neuer-webcast.md',
    previous: {
      tags: [],
      content:
        '<ul><li>I always had an optimism that was hard for others</li><li>Even in the midst of the all the negative influences from family TWhen I was a young man, even a teenager for that matter, I always had an optimism that was</li></ul>\n',
      collection: 'events',
      url: '/events/2022-02-16-neuer-webcast%20copy/',
      relative_path: '_events/2022-02-16-neuer-webcast copy.md',
      next: {
        tags: [],
        collection: 'events',
        url: '/events/2022-02-16-neuer-webcast/',
        relative_path: '_events/2022-02-16-neuer-webcast.md',
        path: '_events/2022-02-16-neuer-webcast.md',
        date: '2022-02-16 00:00:00 +0100',
        title: 'Neue Headline 2. Thema, maximal 2 Zeilig',
        categories: [],
        id: '/events/neuer-webcast',
        draft: false,
        layout: 'event',
        eventid: 1,
        headline: 'Neue Headline 2. Thema, maximal 2 Zeilig',
        authors: 'Mit Nadine Kern & Max Mustermann',
        time: '14-15 Uhr',
        shapes: [{ color: 'var(--color-green-blue)' }, { color: 'var(--color-yellow)' }],
        webcast: true,
        image: { img: '/events/authors/authors-demo.png', alt: 'lorem ipsum' },
        badge: { text: 'Neuer Webcast', icon: '' },
        cta: { text: 'Jetzt anmelden', href: 'javascript:void(0)', skin: 'primary', button: true },
        slug: 'neuer-webcast',
        ext: '.md',
      },
      path: '_events/2022-02-16-neuer-webcast copy.md',
      previous: {
        tags: [],
        collection: 'events',
        url: '/events/2022-02-16-neuer-webcast%20copy%202/',
        relative_path: '_events/2022-02-16-neuer-webcast copy 2.md',
        path: '_events/2022-02-16-neuer-webcast copy 2.md',
        date: '2022-02-16 00:00:00 +0100',
        title: 'Microsoft 365 Holistic Workplace Security via Teams Meeting',
        categories: [],
        id: '/events/neuer-webcast copy 2',
        draft: false,
        layout: 'event',
        eventid: 3,
        headline: 'Microsoft 365 Holistic Workplace Security via Teams Meeting',
        authors: 'Mit Nadine Kern & Max Mustermann',
        time: '1-4 Tage',
        shapes: [{ color: 'var(--color-green-blue)' }, { color: 'var(--color-yellow)' }],
        webcast: true,
        image: { img: '/events/authors/authors-demo.png', alt: 'lorem ipsum' },
        badge: { text: 'Training', color: 'var(--color-sunglow)' },
        price: 'Kostenlos',
        slug: 'neuer-webcast copy 2',
        ext: '.md',
      },
      output: 'event layout\n',
      excerpt:
        '<ul><li>I always had an optimism that was hard for others</li><li>Even in the midst of the all the negative influences from family TWhen I was a young man, even a teenager for that matter, I always had an optimism that was</li></ul>\n',
      date: '2022-02-16 00:00:00 +0100',
      title: 'Neue Headline 2. Thema, maximal 2 Zeilig',
      categories: [],
      id: '/events/neuer-webcast copy',
      draft: false,
      layout: 'event',
      eventid: 2,
      headline: 'Neue Headline 2. Thema, maximal 2 Zeilig',
      authors: 'Mit Nadine Kern & Max Mustermann',
      time: '14-15 Uhr',
      shapes: [{ color: 'var(--color-green-blue)' }, { color: 'var(--color-yellow)' }],
      webcast: true,
      image: { img: '/events/authors/authors-demo.png', alt: 'lorem ipsum' },
      badge: { text: 'Neuer Webcast', icon: '' },
      cta: { text: 'Jetzt anmelden', href: 'javascript:void(0)', skin: 'primary', button: true },
      slug: 'neuer-webcast copy',
      ext: '.md',
    },
    output: 'event layout\n',
    excerpt:
      '<p>Even in the midst of the all the negative influences from family TWhen I was a young man, even a teenager for that matter, I always had an optimism that was</p>\n',
    date: '2022-02-16 00:00:00 +0100',
    title: 'Neue Headline 2. Thema, maximal 2 Zeilig',
    categories: [],
    id: '/events/neuer-webcast',
    draft: false,
    layout: 'event',
    eventid: 1,
    headline: 'Neue Headline 2. Thema, maximal 2 Zeilig',
    authors: 'Mit Nadine Kern & Max Mustermann',
    time: '14-15 Uhr',
    shapes: [{ color: 'var(--color-green-blue)' }, { color: 'var(--color-yellow)' }],
    webcast: true,
    image: { img: '/events/authors/authors-demo.png', alt: 'lorem ipsum' },
    badge: { text: 'Neuer Webcast', icon: '' },
    cta: { text: 'Jetzt anmelden', href: 'javascript:void(0)', skin: 'primary', button: true },
    slug: 'neuer-webcast',
    ext: '.md',
  },
];
