name: Run Tests on Pull Request
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.18
      - uses: actions/checkout@v3
      - name: Install and Build
        run: |
          npm install
          node scripts/generateTests.js
