name: Run Tests on Pull Request
on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11

      - name: Install dependencies
        run: npm ci

      - name: Start Storyboo
        run: npm run storybook &

      - name: Wait for localhost:6006
        run: |
          npx wait-on tcp:localhost:6006 -s -t 30000
          echo "localhost:6006 is running!"

      - name: Run Cypress test
        run: npm run cypress:test

      - name: Stop Storybook
        run: |
          pkill -f "storybook"
          echo "Storybook stopped!"
